### ISSUE TITLE
[Request] Toggleable features

### ISSUE THREAD

**Issue by sleepingdragoninn** [fantahund/EasierEnchanting#2]
It'd be helpful if you could turn off rerolling or turn off showing all enchantments in the config file. Both are good features but sometimes I want just one.

**Comment by fantahund** [comment]
Yes, that's right. I think I'll put that in the next few days.

**Comment by fantahund** [comment]
done https://modrinth.com/mod/easierenchanting/version/1.5.0

**Comment by sleepingdragoninn** [comment]
Perfect! Thanks for that!

It seems like this version runs fine on 1.19.2 (and therefore probably 1.19.3) - Could you mark it like that on modrinth? our pack autoupdater likes to try downgrade the version otherwise.

https://github.com/fantahund/EasierEnchanting/assets/55819817/092d0417-e54b-4962-8f69-3235fba1556d

**Comment by fantahund** [comment]
done
